In [1]:
%load_ext autoreload
%autoreload 2

In [9]:
from dataloader import *


In [31]:
root = '../data'
train = 'training_data'
dev = 'dev_data'
test = 'public_test_data'
data = DataManager(root, train, dev, test)

In [35]:
train = data.get_data('train')

In [36]:
from torch.utils.data import DataLoader
loader = DataLoader(train, batch_size=3, collate_fn=train.collate_fn)

In [37]:
next(iter(loader))

(tensor([[ 1,  2,  3,  4,  5,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
           0,  0],
         [ 7,  1,  8,  9, 10, 11, 12, 13, 14, 15, 16,  5,  6,  0,  0,  0,  0,  0,
           0,  0],
         [17, 18,  1, 19, 20, 21, 22, 23, 15, 24,  5,  6, 25, 11, 13, 26, 27, 28,
          29, 30]]),
 tensor([[ 2, 20, 21, 13, 17, 17,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
           2,  2],
         [ 2,  8, 23,  2,  2, 19,  5,  5,  5,  2, 22, 16, 16,  2,  2,  2,  2,  2,
           2,  2],
         [ 2,  2,  2, 20, 21, 21, 21, 21,  2, 13, 17, 17,  2, 19,  5,  5,  5, 11,
           7,  2]]),
 tensor([7, 7, 7]))

In [40]:
import torch.nn as nn
lstm = nn.LSTM(10, 20, num_layers = 2, bidirectional = True, batch_first = True)

In [48]:
a = torch.rand(3, 1, 10)
lstm(a)[1]

(tensor([[[-8.9968e-02, -2.9833e-02, -3.4203e-02, -1.1474e-02, -3.4472e-02,
           -1.5362e-02, -4.7754e-02,  6.4591e-02, -3.5344e-02,  3.1274e-02,
           -1.2884e-01, -5.2404e-02, -1.7303e-02, -1.6316e-02,  7.5533e-02,
           -8.9221e-02, -1.2874e-01, -2.6565e-02, -5.9550e-02,  4.8886e-02],
          [-6.9775e-02, -8.4969e-02,  6.1669e-04,  7.3075e-03,  6.1066e-02,
            2.6703e-02, -6.1954e-02,  9.3693e-02, -1.4872e-02, -1.2920e-02,
           -1.0353e-01, -4.0956e-02, -3.7248e-02,  3.4098e-02,  7.0620e-02,
           -1.2162e-01, -1.1066e-01, -3.6945e-02, -8.8839e-02,  3.7368e-02],
          [-7.2007e-02, -1.0315e-01, -4.4881e-02, -5.4880e-02,  5.6793e-02,
           -2.8641e-02, -3.6591e-02,  8.1174e-02, -7.3021e-02, -6.0775e-03,
           -9.9125e-02,  1.9607e-02, -4.4066e-02,  3.9119e-02,  1.3172e-01,
           -1.4191e-01, -1.4216e-01, -4.7706e-02, -1.2501e-01,  5.1147e-02]],
 
         [[-1.3237e-01, -4.1896e-02, -8.0365e-02,  1.2564e-02,  2.7093e-02,
      